apimServiceName: apim-pklab-prod
namedValues:
- name: Secret1
    properties:
      displayName: Secret1
      value: "{#Secret1ProdValue#}
  - name: KVSecret1
    properties:
      displayName: KVSecret1
      keyVault:
        identityClientId: 18c5ddef-df59-45b6-859a-e80054157dae
        secretIdentifier: https://apim-pklab-prod-kv.vault.azure.net/secrets/KVSecret1
