apimServiceName: apim-pklab-prod
namedValues:
  - name: KVSecret1
    properties:
      displayName: KVSecret1
      keyVault:
        identityClientId: e29c7cd1-3a0a-4411-8790-0ea003f76a42
        secretIdentifier: https://apim-pklab-prod-kv.vault.azure.net/secrets/KVSecret1
