apimServiceName: apim-pklab-prod
namedValues:
  - name: Secret1
    properties:
      displayName: Secret1
      secret: true
      value: "Secret1ProdValue"
  - name: KVSecret1
    properties:
      displayName: KVSecret1
      keyVault:
        secretIdentifier: https://apim-pklab-prod-kv.vault.azure.net/secrets/KVSecret1
